name: Build & Publish

on:
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.task.name }} py-${{ matrix.python-version }} ${{ matrix.json-lib }} (${{ matrix.os }})
    strategy:
      max-parallel: 4
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: [3.10"]
        task:
          - name: Typecheck
            run: make type-check
          - name: Lint
            run: make lint
          - name: Run tests
            run: make run-tests-w-coverage
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: pdm-project/setup-pdm@main
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: make dev
      - name: ${{ matrix.task.name }}
        run: ${{ matrix.task.run }}
  
  publish:
    needs: [tests]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python 3.10 & PDM
        uses: pdm-project/setup-pdm@main
        with:
          python-version: "3.10"
      - name: Build distribution
        run: |
          pdm build
          echo "github.ref = ${{ github.ref }}"
      - name: Publish package to TestPyPI
        uses: pypa/gh-action-pypi-publish@master
        if: github.repository == 'spraakbanken/text-manipulations-py' && !startsWith(github.ref, 'refs/tags/')
        continue-on-error: true
        with:
          user: __token__
          password: ${{ secrets.test_pypi_password }}
          repository_url: https://test.pypi.org/legacy/
      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@master
        if: github.repository == 'spraakbanken/text-manipulations-py' && startsWith(github.ref, 'refs/tags/')
        with:
          user: __token__
          password: ${{ secrets.pypi_password }}
